Updating package.json to prepare for npm publishing
temyers/serverless-localstack pull request #18
Opened 2017-12-04 15:27 UTC by justinm

This PR updates the package.json in preparation of publishing to NPM. I found the latest contributors to the repo and added them to the contributors list as well.

If/when accepted, as repository owner the honor of publishing the falls to you :)

2017-12-10 06:39 UTC, temyers requested changes
Awesome, thanks for the contribution.

Please can you resolve the conflict and I'll merge.

2017-12-19 07:06 UTC, justinm commented
Conflicts have been resolved, sorry for the delay in getting back to this.

2018-01-09 04:51 UTC, temyers commented
Awesome, apologies for the delay, I'll look at publishing to NPM shortly.

2018-01-09 04:52 UTC, temyers approved these changes

2018-01-09 23:57 UTC, merged